[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read-write", path = "./"}]
auto_detect_solc = false
solc_version = "0.8.24"


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "http://127.0.0.1:3002"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"




# See more config options https://book.getfoundry.sh/reference/config/overview